env_list = ["py313-zarrv2", "py313-zarrv3", "py313-tensorstore-zarr", "py313-tensorstore-n5"]
requires = ["tox>=4.24"]

[env.py313-tensorstore-zarr]
commands = [
    [
        "pytest",
        "--benchmark-save=tensorstore-zarr",
        "--benchmark-save-data",
        "-m",
        "tensorstore and not n5",
        {extend = true, replace = "posargs"},
    ],
]
description = "Run Zarr benchmarks under tensorstore"
extras = ["tensorstore"]

[env.py313-tensorstore-n5]
commands = [
    [
        "pytest",
        "--benchmark-save=tensorstore-n5",
        "--benchmark-save-data",
        "-m",
        "n5",
        {extend = true, replace = "posargs"},
    ],
]
description = "Run N5 benchmarks under tensorstore"
extras = ["tensorstore"]

[env.py313-zarrv2]
commands = [
    [
        "pytest",
        "--benchmark-save=zarr-python-v2",
        "--benchmark-save-data",
        "-m",
        "zarr_python",
        {extend = true, replace = "posargs"},
    ],
]
description = "Run benchmarks under zarr-python version 2"
extras = ["zarr-python-v2"]

[env.py313-zarrv3]
commands = [
    [
        "pytest",
        "--benchmark-save=zarr-python-v3",
        "--benchmark-save-data",
        "-m",
        "zarr_python",
        {extend = true, replace = "posargs"},
    ],
]
description = "Run benchmarks under zarr-python version 3"
extras = ["zarr-python-v3"]
